name: Ubuntu

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          mkdir -p build
          cd build
          cmake ../ -DBUILD_TESTS=ON
          cmake --build . --target test_jsoncons --config Release
          make -j2 test_jsoncons