name: MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake . -DBUILD_TESTS=on

    - name: Build
      run: cmake --build . --target test_jsoncons --config Release

    - name: Run unit tests
      working-directory: tests
      run: ./test_jsoncons
