name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: mkdir -p ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        echo $GITHUB_WORKSPACE
        cmake $GITHUB_WORKSPACE -DBUILD_TESTS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        echo $GITHUB_WORKSPACE
        cmake --build $GITHUB_WORKSPACE --target test_jsoncons --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build/tests/Release
      shell: bash
      run: ./test_jsoncons
