name: Ubuntu

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ../ -DBUILD_TESTS=ON
        cmake --build . --target test_jsoncons --config Release

    - name: Run unit tests
      run: ../build/tests/Release/test_jsoncons
