name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        cmake . -DBUILD_TESTS=on

    - name: Compile
      run: |
        make -j2 test_jsoncons

    - name: Run unit tests
      run: |
        cd tests
        ./test_jsoncons
