name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure CMake
      uses: lukka/run-cmake@v3
      with:
        cmakeGenerator: 'VS16Win64'
        cmakeBuildType: 'Release'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ github.workspace }}'
        cmakeAppendedArgs: ' -DBUILD_TESTS=on'
        buildWithCMake: true
        buildWithCMakeArgs: '--config Release'

    - name: Build
      run: cmake --build . --target test_jsoncons --config Release

    - name: Run unit tests
      working-directory: tests
      run: .\Release\test_jsoncons
