name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest CMake and ninja
      # Using 'latest' branch, the latest CMake and ninja are installed.
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -G Ninja -D BUILD_TESTS=1 .
      # uses: lukka/run-cmake@v3
      # with:
      #   cmakeGenerator: 'VS16Win64'
      #   buildDirectory: '${{ github.workspace }}'
      #   cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
      #   cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
      #   cmakeAppendedArgs: '-DBUILD_TESTS=on'
      shell: cmd

    - name: Build
      run: cmake --build . --target test_jsoncons --config Release
      shell: cmd

    - name: Run unit tests
      working-directory: tests/
      run: |
        .\Release\test_jsoncons
      shell: cmd
